# Generated by Django 2.2.12 on 2020-04-19 14:20

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Website',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('website_name', models.CharField(max_length=255)),
                ('product_name', models.CharField(max_length=255)),
                ('plan', models.IntegerField()),
                ('payment_amount', models.FloatField()),
                ('template_id', models.IntegerField()),
                ('company_name', models.CharField(max_length=255)),
                ('twitter_profile', models.CharField(max_length=255)),
                ('facebook_profile', models.CharField(max_length=255)),
                ('product_description', models.CharField(max_length=512)),
                ('product_image_url', models.CharField(max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
